### ISSUE TITLE
How to export 3DOs?

### ISSUE THREAD

**Issue by mckittrick14** [r1sc/OpenSith#4]
Hey @r1sc, I really appreciate you sharing this code. I was able to use the Oculus Integration package to put this childhood classic into VR. I'm trying to use this project to learn Unity and C#. I'm having a difficult time exporting the 3DOs from the .GOB file and keeping them as assets in my project (i.e., I can only access the 3DOs in game mode). How can I make this happen?

**Comment by r1sc** [comment]
OpenSith was always about building an engine that reads the original data files at runtime and bundles as little content as possible. That said, if you want to import assets offline, I'd suggest you start looking at https://docs.unity3d.com/Manual/ScriptedImporters.html. You could probably repurpose the original code that builds gameobjects at runtime to work offline with a scripted importer.

However, all file formats used by Jedi Knight are ASCII-text, so parsing the assets is very straight forward. There probably exists other offline conversion methods built by the community over the years.
